---
title: "Practical 8"
author: "Olivier Gimenez"
date: "last updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, "slides-theme.css"]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
      titleSlideClass: [center, middle]
---

```{r setup, include=FALSE, echo=FALSE}
#options(htmltools.dir.version = FALSE)
#knitr::opts_chunk$set(comment = "", warning = FALSE, message = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(palmerpenguins)
library(tidyverse)
```

## Model selection with wAIC

* Consider the plant example. 

* Compare the three models (no, partial and complete pooling) with wAIC.

---

# Solution

---
## wAIC of model with no pooling

```{r eval = FALSE}
samples <- jags.samples(model = allom.1$model,
                        variable.names = c("WAIC", "deviance"), 
                        type = "mean", 
                        n.iter = 2000, 
                        n.burnin = 1000, 
                        n.thin = 1)
samples$p_waic <- samples$WAIC
samples$waic <- samples$deviance + samples$p_waic
tmp <- sapply(samples, sum)
waic_completepooling <- round(c(waic = tmp[["waic"]], 
                                p_waic = tmp[["p_waic"]]),1)
```

---
## wAIC of model with partial pooling

```{r eval = FALSE}
samples <- jags.samples(model = allom.2$model,
                        variable.names = c("WAIC","deviance"), 
                        type = "mean", 
                        n.iter = 2000, 
                        n.burnin = 1000, 
                        n.thin = 1)
samples$p_waic <- samples$WAIC
samples$waic <- samples$deviance + samples$p_waic
tmp <- sapply(samples, sum)
waic_partialpooling <- round(c(waic = tmp[["waic"]], 
                               p_waic = tmp[["p_waic"]]),1)
```

---
## wAIC of model with complete pooling

```{r eval = FALSE}
samples <- jags.samples(model = allom.3$model,
                        variable.names = c("WAIC","deviance"), 
                        type = "mean", 
                        n.iter = 2000, 
                        n.burnin = 1000, 
                        n.thin = 1)
samples$p_waic <- samples$WAIC
samples$waic <- samples$deviance + samples$p_waic
tmp <- sapply(samples, sum)
waic_nopooling <- round(c(waic = tmp[["waic"]], 
                          p_waic = tmp[["p_waic"]]),1)
```

---
## Model ranking

```{r eval = FALSE}
data.frame(model = c('no pooling', 
                     'partial pooling', 
                     'complete pooling'),
           waic = c(waic_nopooling[1],
                    waic_partialpooling[1],
                    waic_completepooling[1]),
           p_waic = c(waic_nopooling[2],
                      waic_partialpooling[2],
                      waic_completepooling[2])) %>%
  arrange(waic)
```

---
## Model ranking

```{r echo=FALSE}
load(here::here("slides/dat/waic.RData"))
waic
```
